{cache: {directories: [.cache/bootstrap]}, env: {matrix: [IJ_ULTIMATE=false, IJ_ULTIMATE=true,
      PANTS_SHA="release_1.1.0-pre3" TEST_SET=integration, PANTS_SHA="release_1.1.0-pre2"
        TEST_SET=integration, PANTS_SHA="release_1.1.0-pre1" TEST_SET=integration]},
  install: ./scripts/setup-ci-environment.sh, jdk: [oraclejdk8], language: java, notifications: {
    email: [yic@twitter.com, fedor.korotkov@gmail.com]}, script: [./scripts/run-tests-ci.sh],
  sudo: false}
