{cache: {directories: [.cache/bootstrap, .cache/pants]}, env: {matrix: [IJ_ULTIMATE=false,
      IJ_ULTIMATE=true, PANTS_SHA="release_1.1.0-pre3" TEST_SET=jvm-integration, PANTS_SHA="release_1.1.0-pre2"
        TEST_SET=jvm-integration, PANTS_SHA="release_1.1.0-pre1" TEST_SET=jvm-integration]},
  install: ./scripts/setup-ci-environment.sh, jdk: [oraclejdk8], language: java, notifications: {
    email: [yic@twitter.com, fedor.korotkov@gmail.com]}, script: [./scripts/run-tests-ci.sh],
  sudo: false}
