{cache: {directories: [.cache/bootstrap, .cache/pants]}, dist: trusty, env: {matrix: [
      IJ_ULTIMATE=false, IJ_ULTIMATE=true, PANTS_SHA="release_1.2.0-dev3" TEST_SET=jvm-integration,
      PANTS_SHA="release_1.2.0-dev2" TEST_SET=jvm-integration, PANTS_SHA="release_1.2.0-dev1"
        TEST_SET=jvm-integration]}, install: ./scripts/setup-ci-environment.sh, jdk: [
    oraclejdk8], language: java, notifications: {email: [yic@twitter.com, fedor.korotkov@gmail.com]},
  script: [./scripts/run-tests-ci.sh], sudo: required}
